language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: false
install:
- pip install git+git://github.com/mraspaud/aggdraw.git
- python setup.py install
- pip install coveralls
script: coverage run --source=pycoast setup.py test
after_success: coveralls
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt